name: Prod pipeline

on:                                                                                                                                                                                                                   
 push:                                                                                                                                                                                                                                 
    tags:                                                                                                                                                                                                               
    - "[0-9]+.[0-9]+.[0-9]+"

jobs:
    aws_cdk_tag:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
    
          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v1
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ env.AWS_REGION }}
    
          - name: install npm
            run: 'sudo apt update -y && sudo apt install nodejs npm -y'
    
          - name: Install AWS CDK
            run: 'sudo npm install -g aws-cdk'
    
          - name: Install Requirements
            run: |
              npm ci
              npm run build             
            working-directory: .
    
          - name: CDK Synth
            run: cdk synth
            working-directory: .
                  
          - name: CDK bootstrap
            run: cdk bootstrap
            working-directory: .
    
          - name: CDK Deploy
            run: cdk deploy --require-approval never --verbose
            working-directory: .
            
          - name: CDK Destroy
            run: cdk destroy --force
            working-directory: .