name: Git Tag Release!!

on:
  workflow_dispatch:
    
jobs:
  git-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_KEY }}

      - name: Approve tag creation
        uses: trstringer/manual-approval@v1
        timeout-minutes: 15
        with:
          secret: ${{ github.Token }}
          approvers: SumptaOj

      # - name: Pull latest changes
      #   run: git pull origin main

      - name: Extract Package Version
        id: extract
        run: |
          PACKAGE_VERSION=$(jq -r .version package.json)
          echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> "$GITHUB_OUTPUT"

      - name: Get The Current Tag
        id: current
        run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_OUTPUT

      - name: Create tag
        run: |
          PACKAGE_VERSION=${{ steps.extract.outputs.PACKAGE_VERSION }}
          git tag $PACKAGE_VERSION
          git push origin $PACKAGE_VERSION

      - name: Create release note
        id: release_notes
        run: |
          previous_tag=${{ steps.current.outputs.GIT_TAG }}
          release_notes=$(git log --pretty=format:"%s%n%b" $previous_tag..HEAD)
          echo "release_notes=$release_notes" >> $GITHUB_OUTPUT

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract.outputs.PACKAGE_VERSION }}
          release_name: ${{ steps.extract.outputs.PACKAGE_VERSION }}
          body: ${{ steps.release_notes.outputs.release_notes }}